# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0IEB8ryJs4i7KnGTpL6ZRZEBvt_8OQu

### Calculadora
"""



nome_usuario = input('Por favor, digite seu nome: ')
print(f'Olá {nome_usuario}, Seja bem vindo ao meu projeto de calculadora!')


resposta_apresentação = input('Gostaria de uma pequena apresentação sobre o projeto? ')
while True:
    if resposta_apresentação.lower() == 'sim':
        print('Minha calculadora realiza operações com sete operadores: adição (+), subtração (-), multiplicação (*), divisão (/), divisão inteira (//), resto da divisão (%) e exponenciação (**).')
        print('Para obter o resultado de uma operação, você deve inserir primeiro o valor inicial (valor1), em seguida o segundo valor (valor2) e, por fim, informar um dos operadores listados acima para executar o cálculo desejado.')

        resposta_apresentação2 = input('Entendeu como ela funciona? ')
        if resposta_apresentação2.lower() == 'sim':
            print('Então vamos direto para os cálculos!')
            break
        elif resposta_apresentação2.lower() == 'não' or resposta_apresentação2.lower() == 'nao':
            print('Não se preocupe, é apenas uma calculadora. Vamos aprender na prática!')
            break
        else:
            print('Entrada inválida. Por favor, digite "Sim" ou "Não".')


    elif resposta_apresentação.lower() == 'não' or resposta_apresentação.lower() == 'nao':
        print('Então vamos direto para os cálculos!')
        break
    else:
        resposta_apresentação = input('Entrada inválida. Por favor, digite "Sim" ou "Não": ')

# Inicializa 'resultado' para a primeira execução fora do loop
resultado = None
# Inicializa variáveis de controle para a primeira iteração começar corretamente
continuar_operacao = 'sim'
usar_resultado_anterior = 'não'

# Loop principal para múltiplas operações
while continuar_operacao.lower() == 'sim': # Usa uma variável de controle para gerenciar o loop
    # Parte 1: Obter valor1
    if resultado is not None and usar_resultado_anterior.lower() == 'sim':
        valor1 = resultado
        print(f'Usando o resultado anterior ({valor1}) como primeiro valor.')
    else:
        while True: # Loop para obter um valor1 válido
            try:
                valor1 = float(input('Digite o primeiro valor: '))
                break
            except ValueError:
                print('Entrada inválida. Por favor, digite um número válido.')

    # Parte 2: Obter valor2
    while True: # Loop para obter um valor2 válido
        try:
            valor2 = float(input('Digite o segundo valor: '))
            break
        except ValueError:
            print('Entrada inválida. Por favor, digite um número válido.')

    operador = input('Digite o operador: ')


    resultado = None

    # criando as condições da calculadora
    if operador == '+':              # adição
        resultado = valor1 + valor2

    elif operador == '-':            # subtração
        resultado = valor1 - valor2

    elif operador == '*':            # multiplicação
        resultado = valor1 * valor2

    elif operador == '/':            # divisão
        if valor2 == 0:
            print('Não é possível dividir um número por zero')
        else:
            resultado = valor1 / valor2

    elif operador == '//':           # divisão inteira
        if valor2 == 0:
            print('Não é possível dividir um número por zero')
        else:
            resultado = valor1 // valor2

    elif operador == '%':            # resto da divisão
        if valor2 == 0:
            print('Não é possível calcular o resto da divisão por zero')
        else:
            resultado = valor1 % valor2

    elif operador == '**':           # exponenciação
        resultado = valor1 ** valor2

    else:                            # caso informe um caracter que não está em uma das condições retorna como inválido
        print(f'Operador inválido: {operador}')

    # executando a calculadora e imprimindo um resultado se houver
    if resultado is not None:
        print(f'O resultado da operação é: {resultado}')
    else:
        resultado = None

    # Pergunta se o usuário quer fazer outra operação
    temp_continuar_input = input('Deseja realizar outra operação? (Sim/Não): ')
    if temp_continuar_input.lower() == 'sim':
        continuar_operacao = 'sim'
        if resultado is not None: # Verifica se há um resultado anterior
            usar_resultado_anterior = input('Deseja usar o resultado anterior como o primeiro valor? (Sim/Não): ')
            if usar_resultado_anterior.lower() not in ['sim', 'não', 'nao']:
                print('Entrada inválida. Por favor, digite "Sim" ou "Não". Não será usado o resultado anterior.')
                usar_resultado_anterior = 'não'
        else:
            usar_resultado_anterior = 'não'
        print('Então vamos para um novo cálculo!')
    elif temp_continuar_input.lower() == 'não' or temp_continuar_input.lower() == 'nao':
        continuar_operacao = 'não'
        print('Obrigado por usar a calculadora!')
    else:
        print('Entrada inválida. Por favor, digite "Sim" ou "Não". Encerrando a calculadora.')
        continuar_operacao = 'não'



